on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrxyzzyx.azurecr.io
        username: ${{ secrets.acr_acrxyzzyx_username }}
        password: ${{ secrets.acr_acrxyzzyx_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/13/alpine" -f  "13/alpine/Dockerfile" -t acrxyzzyx.azurecr.io/kubernetescluster1:${{ github.sha }} --label dockerfile-path=13/alpine/Dockerfile
        docker push acrxyzzyx.azurecr.io/kubernetescluster1:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kubernetescluster1_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kubernetes-cluster1bbfc | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kubernetes-cluster1bbfc`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kubernetes-cluster1bbfc
        container-registry-url: acrxyzzyx.azurecr.io
        container-registry-username: ${{ secrets.acr_acrxyzzyx_username }}
        container-registry-password: ${{ secrets.acr_acrxyzzyx_password }}
        secret-name: kubernetescldockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kubernetes-cluster1bbfc
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          acrxyzzyx.azurecr.io/kubernetescluster1:${{ github.sha }}
        imagepullsecrets: |
          kubernetescldockerauth
